---
title: "functions_practice"
format: html
editor: visual
---

#q1

```{r}

pred <- read_csv("../data/Utqiagvik_predator_surveys.csv")

egg <- read_csv("../data/Utqiagvik_egg_measurements.csv")
  
nest <- read_csv("../data/Utqiagvik_nest_data.csv")
```

```{r}
webpage <- rvest::read_html("https://www.pwrc.usgs.gov/BBL/Bander_Portal/login/speclist.php")

tbls <- rvest::html_nodes(webpage, "table") %>% 
    rvest::html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    janitor::clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))

head(species, 3)
```



```{r}
#exploring

colnames(pred)
glimpse(pred)
unique(pred$species)
summary(pred)

```

#q2

```{r}

pred_comm_names <- left_join(pred, species, by = c("species" = "alpha_code"))

```

#q3

```{r}
library(dplyr)

species_join <- function(df, species){
  left_join(pred, species, by =  c("species"= "alpha_code")) %>% 
    data.frame()
}

```



```{r}
assign_species_name <- function(df, species) {
  df_species <- left_join (df, species, by - c("species" = "alpha_code"))
  return(df_species)
  
}

```

```{r}


```

